name: Go

on:
  push:
    branches: [ builds390x-vi ]
  pull_request:
    branches: [ builds390x-vi ]

jobs:
  test:
    name: alltests
    runs-on: [self-hosted,go]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup correct Go version
      uses: actions/setup-go@v2
      with:
        go-version: '1.19.10'
        check-latest: true

    - name: alltests
      run: |
        rm -rf /root/go/src/github.com/IBM
        mkdir -p /root/go/src/github.com/IBM/
        mv /tmp/github-runner-your-repo/portieris/portieris /root/go/src/github.com/IBM/
        cd /root/go/src/github.com/IBM/portieris/
        export PATH=$PATH:/usr/local/go/bin/
        export GOPATH=$HOME/go
        export PATH=$PATH:$HOME/go/bin/
        export TERM=ansi

  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/s390x
      - name: test
        run: |
          buildx
  # buildx:
  #     runs-on: ubuntu-latest
  #     strategy:
  #       fail-fast: false
  #       matrix:
  #         buildx-version:
  #           - "latest"
  #     steps:
  #       -
  #         name: Checkout
  #         uses: actions/checkout@v4
  #       -
  #         name: Set up Docker Buildx
  #         id: buildx
  #         uses: ./
  #         with:
  #           version: ${{ matrix.buildx-version }}
  #       -
  #         name: Nodes output
  #         run: |
  #           cat << EOF
  #           ${{ steps.buildx.outputs.nodes }}
  #           EOF
  # install:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v4
  #     -
  #       name: Set up Docker Buildx
  #       uses: ./
  #       with:
  #         install: true
  #     -
  #       name: Check cmd
  #       run: |
  #         docker build --help
  # platforms:
  #   runs-on: ubuntu-latest
  #   steps:
  #     -
  #       name: Checkout
  #       uses: actions/checkout@v4
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #     -
  #       name: Set up Docker Buildx
  #       uses: ./
  #       with:
  #         platforms: linux/s390x
# make alltests
# mv /root/go/src/github.com/IBM/portieris/ /tmp/github-runner-your-repo/portieris/
